### ISSUE TITLE
Define group and event url structure 

### ISSUE THREAD

**Issue by willbeaumont** [social-plan-it/plan-it-social-web#51]
- Architect a URL structure for groups and events. With the following requirements:
  - A group has many events
  - We want to support standalone events without the need for a group
  - A user can create a group
  - A user can edit a group
  - A user can create an event
  - A user can edit an event
  - A user can see a event details page
  - A user can see a group details page
  - User should have an overview of all their events
  - User should have an overview of all their groups.
We already have parts of the pages and some pages in the designs!

**Comment by willbeaumont** [comment]
Should this be 2 issues? Seems like 2 tasks, but I can see how we'd want to have some continuity

**Comment by willbeaumont** [comment]
How about something like this for our URL structure? I'm not sure what the best way for us to talk about this...maybe a markdown file that can be commented on as part of PR?

Existing:
* `/groups` view groups
* `/groups/new` create a new group

Group pages:
* `:groupId` view specific group
* `:groupId/edit` edit group, only allowed for authorized users
* `planitsocial` idea for a special shared groupId for events w/o a specific group (maybe we make this more local/geo based too?)

I'm inclined to change the group structure from the wire frame to use the `:groupId` parameter directly versus a `group/:groupId` structure. If groups are given a unique name, this will help keep our URL length a little shorter. 

Event pages:
* `:groupId/events` view groups events
* `:groupId/events/new` create a new event tied to group
* `:groupid/event/:eventId` view specific event
* `:groupId/event/:eventId/edit` edit a specific event
* `event/:eventId` event without a group
* `event/:eventId/edit` edit event without a group

User pages:
* `my-groups` view logged in user's groups
* `my-events` view logged in user's events

**Comment by andrelandgraf** [comment]
Great work! Awesome that you looked into this!

Big fan of: `groups/:groupId`. With standalone `/:groupId`, we have to be cautious in the future when adding other top-level dynamic routes.

I would try to map the URL as close as possible to the model hierarchy: `groups/:groupId/events/:eventId`. This should help us be flexible in the future when adding more models!

Same with the user routes, maybe: `users/:userId/courses` and `users/:userId/events`?

How could we also allow standalone events without adding a `socialplanit` fake group id? Could we make `groups/:groupId` optional maybe?

For nice URLs: maybe we allow the user to add a nice URL path for groups/events that are unique across social plan-it (optional)?

Like: `e/my-cool-event`?

**Comment by tonydangblog** [comment]
I think namespacing with `/groups/:groupId` rather than just standalone `/:groupId` is a good idea. However, I'm also a fan of keeping URLs as short as possible so that it's easier for users to type and share.

Perhaps we can have the best of both worlds by abbreviating the namespace name for URLs that are more likely shared? For example:

- `/groups/:groupId` -> `/g/:groupId`
-  `/groups/:groupId/events/:eventId` -> `/g/:groupId/e/:eventId`
- `/users/:userId` -> `/u/:userId`


I believe I've seen this pattern used before. Some examples: `reddit.com/r/<sub-reddit-name>` and `linkedin.com/in/<user-name>`.

For URLs that aren't likely to be shared, we can use more explicit naming. For example:

- `/g/:groupId/e/new`

The abbreviated names might get confusing for us as developers, but I think it's a UX improvement since my assumption is that most users would prefer short URLs that can be easily copied & pasted to share or even print on event flyers.
