### ISSUE TITLE
[BUG]: User is notified they are logging out when clicking "Home" navigation

### ISSUE THREAD

**Issue by willbeaumont** [social-plan-it/plan-it-social-web#56]
When logged in and I press the home navigation page. I'm informed that I am logging out, but did not want to do this nor am I actually logged out. 

The `isSubmitting` navigation state is suspect, maybe there is a way it can check for submitting/loading only after a logout click.

Steps to reproduce:
1. Login
<img width="1105" alt="Pasted Graphic" src="https://github.com/social-plan-it/plan-it-social-web/assets/39424606/d4e2e27d-0ea5-4ce0-acac-d89a3a0ca065">
2. Press "Home" in top-nav
<img width="1090" alt="Pasted Graphic 2" src="https://github.com/social-plan-it/plan-it-social-web/assets/39424606/6edb76bf-313d-43ae-ac3e-0b8109a566a8">

**Comment by andrelandgraf** [comment]
Great find! That's the difference between Remix's `Form` and `useFetcher`! Let's discuss this in one of the upcoming sessions!

**Comment by tonydangblog** [comment]
Good find! I mentioned this being a potential problem in my comments on PR #55. 

This occurs because we're using `navigation.state === 'submitting' || navigation.state === 'loading'` to determine when the log out form is being submitted. I thought this would only be a problem if we had multiple forms on a page on a page, but didn't account for the fact that the loader function is also being called on navigation. Definitely interested in hearing if there's a standard way of addressing this issue in a future session!

**Comment by tonydangblog** [comment]
I looked into this a little further today and found a possibly simpler solution using `navigation.formAction === '/logout'` to check which form is currently being submitted. Not sure if there are downsides to using `navigation.formAction` vs `useFetcher`. 

I'll go ahead and submit a PR for this and we can review in our next call :)
